name: Build, Test and Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Upgrade pip and install requests
      run: python -m pip install --upgrade build requests
    - name: Download the NAIF high precision EOP file
      run: python naif_eop_high_prec/fetch.py
    - name: Set Version
      run: |
        VERSION=$(date -u +%Y.%m.%d)
        sed -i "s/.*version =.*/version = \"$VERSION\"/g" pyproject.toml
    - name: Install naif_eop_high_prec
      run: pip install .[tests]
    - name: Test naif_eop_high_prec
      run: pytest .
    - name: Build Source Distribution and Wheel
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish naif_eop_high_prec to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
